Revert ProcessMessage change for block
Reverts a change that generates the following, further investigation is required to check the expected behaviour of the code. The revert here is a quick fix.

EXCEPTION: N5boost16exception_detail10clone_implINS0_19error_info_injectorISt12out_of_rangeEEEE
Unable to find key in unordered_map.
electra in ProcessMessages()

2019-04-13 12:22:43 ProcessMessages(block, 439 bytes) FAILED peer=1